### ISSUE TITLE
Read CCD bus?

### ISSUE THREAD

**Issue by causalloop** [Alexia/CAN-CCD_bus#1]
I'm interested in being able to extract data from the existing BUS, not just write to it, but all I see is basically how to write/send data to the gauge cluster.  Do you have any material on reading the incoming data since there's no OBD2?  I've a 93 ZJ V8 and an old Snapon I got off Ebay, but I'm not about to mount that sucker in the dashboard just cause I want more data ;-)

Thanks!

**Comment by Alexia** [comment]
I have not got to that part of the project yet.  Doing so will require building a CCD compliant bus transceiver instead of using a CAN bus transceiver.  While a CAN bus transceiver works to transmits on CCD bus it does not receive due to a small difference in how CCD and CAN power the bus lines.
